# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QTableView, QMessageBox
from src import InfoForm, InputForm
from src import FollowTableViewmodel as fviewmodel
from src import InputFormViewmodel as inputviewmodel
from src import FollowListModel as flist
from src import BlackListModel as blist

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_fo_manuallyAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fo_manuallyAdd.setGeometry(QtCore.QRect(320, 160, 111, 41))
        self.pushButton_fo_manuallyAdd.setObjectName("pushButton_fo_manuallyAdd")
        self.pushButton_fo_updateList = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fo_updateList.setGeometry(QtCore.QRect(320, 100, 111, 41))
        self.pushButton_fo_updateList.setObjectName("pushButton_fo_updateList")
        self.pushButton_fo_manuallyDel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fo_manuallyDel.setGeometry(QtCore.QRect(320, 220, 111, 41))
        self.pushButton_fo_manuallyDel.setObjectName("pushButton_fo_manuallyDel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(450, -30, 20, 601))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_fo_searchbar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fo_searchbar.setGeometry(QtCore.QRect(230, 30, 71, 31))
        self.pushButton_fo_searchbar.setObjectName("pushButton_fo_searchbar")
        self.pushButton_fo_clearAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fo_clearAll.setGeometry(QtCore.QRect(320, 280, 111, 41))
        self.pushButton_fo_clearAll.setObjectName("pushButton_fo_clearAll")
        self.tableView_fo = QtWidgets.QTableView(self.centralwidget)
        self.tableView_fo.setGeometry(QtCore.QRect(40, 70, 261, 381))
        self.tableView_fo.setObjectName("tableView_fo")
        self.tableView_black = QtWidgets.QTableView(self.centralwidget)
        self.tableView_black.setGeometry(QtCore.QRect(490, 50, 131, 241))
        self.tableView_black.setObjectName("tableView_black")
        self.pushButton_black_manuallyAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_black_manuallyAdd.setGeometry(QtCore.QRect(640, 100, 111, 41))
        self.pushButton_black_manuallyAdd.setObjectName("pushButton_black_manuallyAdd")
        self.pushButton_black_manuallyDel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_black_manuallyDel.setGeometry(QtCore.QRect(640, 160, 111, 41))
        self.pushButton_black_manuallyDel.setObjectName("pushButton_black_manuallyDel")
        self.pushButton_black_clearAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_black_clearAll.setGeometry(QtCore.QRect(640, 220, 111, 41))
        self.pushButton_black_clearAll.setObjectName("pushButton_black_clearAll")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(460, 310, 341, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_fo_searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fo_searchBar.setGeometry(QtCore.QRect(40, 30, 181, 31))
        self.lineEdit_fo_searchBar.setObjectName("lineEdit_fo_searchBar")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(320, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalSlider_catchFreq = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_catchFreq.setGeometry(QtCore.QRect(560, 370, 160, 22))
        self.horizontalSlider_catchFreq.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_catchFreq.setObjectName("horizontalSlider_catchFreq")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 370, 72, 15))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(730, 370, 72, 15))
        self.label_4.setObjectName("label_4")
        self.lineEdit_catchNumPerGroup = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_catchNumPerGroup.setGeometry(QtCore.QRect(570, 408, 171, 24))
        self.lineEdit_catchNumPerGroup.setObjectName("lineEdit_catchNumPerGroup")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 410, 91, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(475, 450, 91, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_catchCycle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_catchCycle.setGeometry(QtCore.QRect(570, 450, 171, 24))
        self.lineEdit_catchCycle.setObjectName("lineEdit_catchCycle")
        self.radioButton_STmode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_STmode.setGeometry(QtCore.QRect(480, 500, 115, 19))
        self.radioButton_STmode.setObjectName("radioButton_STmode")
        self.radioButton_TPWMode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TPWMode.setGeometry(QtCore.QRect(560, 500, 111, 16))
        self.radioButton_TPWMode.setObjectName("radioButton_TPWMode")
        self.radioButton_MIXmode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_MIXmode.setGeometry(QtCore.QRect(650, 500, 115, 19))
        self.radioButton_MIXmode.setObjectName("radioButton_MIXmode")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 490, 381, 41))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_progress = QtWidgets.QLabel(self.centralwidget)
        self.label_progress.setGeometry(QtCore.QRect(320, 450, 91, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_progress.setFont(font)
        self.label_progress.setObjectName("label_progress")
        self.pushButton_start_now = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_now.setGeometry(QtCore.QRect(335, 370, 81, 31))
        self.pushButton_start_now.setObjectName("pushButton_start_now")
        self.pushButton_pause_now = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pause_now.setGeometry(QtCore.QRect(335, 410, 81, 31))
        self.pushButton_pause_now.setObjectName("pushButton_pause_now")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_instruction = QtWidgets.QAction(MainWindow)
        self.action_instruction.setObjectName("action_instruction")
        self.action_checkUpdate = QtWidgets.QAction(MainWindow)
        self.action_checkUpdate.setObjectName("action_checkUpdate")
        self.actionz = QtWidgets.QAction(MainWindow)
        self.actionz.setObjectName("actionz")
        self.actionh = QtWidgets.QAction(MainWindow)
        self.actionh.setText("")
        self.actionh.setObjectName("actionh")
        self.action_unlockMore = QtWidgets.QAction(MainWindow)
        self.action_unlockMore.setObjectName("action_unlockMore")
        self.action_author_info = QtWidgets.QAction(MainWindow)
        self.action_author_info.setObjectName("action_author_info")
        self.actiond_annouce = QtWidgets.QAction(MainWindow)
        self.actiond_annouce.setObjectName("actiond_annouce")
        self.menu.addAction(self.action_instruction)
        self.menu.addAction(self.action_checkUpdate)
        self.menu.addAction(self.action_unlockMore)
        self.menu.addAction(self.action_author_info)
        self.menu.addAction(self.actiond_annouce)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FurTwiiCrawler 毛推抓"))
        MainWindow.setWindowIcon(QIcon("./icon.ico"))
        self.pushButton_fo_manuallyAdd.setText(_translate("MainWindow", "手动添加"))
        self.pushButton_fo_updateList.setText(_translate("MainWindow", "更新列表"))
        self.pushButton_fo_manuallyDel.setText(_translate("MainWindow", "手动删除"))
        self.pushButton_fo_searchbar.setText(_translate("MainWindow", "查找"))
        self.pushButton_fo_clearAll.setText(_translate("MainWindow", "清空列表"))
        self.pushButton_black_manuallyAdd.setText(_translate("MainWindow", "手动添加"))
        self.pushButton_black_manuallyDel.setText(_translate("MainWindow", "手动删除"))
        self.pushButton_black_clearAll.setText(_translate("MainWindow", "清空列表"))
        self.label_1.setText(_translate("MainWindow", "抓取列表"))
        self.label_2.setText(_translate("MainWindow", "过滤名单"))
        self.label_3.setText(_translate("MainWindow", "设置"))
        self.label.setText(_translate("MainWindow", "抓取频率"))
        self.label_4.setText(_translate("MainWindow", "1.5s"))
        self.label_5.setText(_translate("MainWindow", "单次抓取数"))
        self.label_6.setText(_translate("MainWindow", "单次抓取间隔"))
        self.radioButton_STmode.setText(_translate("MainWindow", "ST模式"))
        self.radioButton_TPWMode.setText(_translate("MainWindow", "TPW模式"))
        self.radioButton_MIXmode.setText(_translate("MainWindow", "MIX模式"))
        self.label_progress.setText(_translate("MainWindow", "进度指示条"))
        self.menu.setTitle(_translate("MainWindow", "更多信息"))
        self.action_instruction.setText(_translate("MainWindow", "使用说明"))
        self.action_checkUpdate.setText(_translate("MainWindow", "查找更新"))
        self.actionz.setText(_translate("MainWindow", "作者信息"))
        self.action_unlockMore.setText(_translate("MainWindow", "解锁功能"))
        self.action_author_info.setText(_translate("MainWindow", "作者信息"))
        self.actiond_annouce.setText(_translate("MainWindow", "声明"))
        self.pushButton_start_now.setText(_translate("MainWindow", "开始抓图"))
        self.pushButton_pause_now.setText(_translate("MainWindow", "暂停抓图"))
        
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    inputForm = QtWidgets.QMainWindow()
    inputform_ui = InputForm.Ui_Form_Input()
    inputform_ui.setupUi(inputForm)
    #inputForm.show()
    infoForm = QtWidgets.QMainWindow()
    infoform_ui = InfoForm.Ui_Form_instruction()
    infoform_ui.setupUi(infoForm)
    the_fo_list_model = flist.FollowingListModel()
    the_ban_list_model = blist.BlackListModel()
    fvm = fviewmodel.FollowingTableViewmodel(the_fo_list_model,ui.tableView_fo,inputForm,ui.pushButton_fo_updateList,
                                             ui.pushButton_fo_manuallyAdd,ui.pushButton_fo_manuallyDel,
                                             ui.pushButton_fo_clearAll,MainWindow)
    inputvm = inputviewmodel.InputFormViewmodel(the_fo_list_model,inputform_ui,inputForm,fvm,ui)
    #inputform_ui.pushButton_i_can.clicked.connect(inputvm.on_clicked_i_can)
    #ui.pushButton_fo_updateList.clicked.connect(fvm.on_clickUpdate)
    #inputform_ui.pushButton_i_cant.clicked.connect(inputvm.on_clicked_i_cant)
    sys.exit(app.exec_())